<?php

declare(strict_types=1);

if (\class_exists('WP_Block_Patterns_Registry')) {
    \add_action('init', function () {
        \register_block_pattern(
            'boxernia/bsk__page-cadre',
            [
                'title' => \__('BSK - strona Kadra', 'Boxernia'),
                'content' => '<!-- wp:acf/banner-block {"id":"block_640c46a6bcbf2","name":"acf/banner-block","data":{"banner-title":"Kadra","_banner-title":"banner-title_key","tag-title":"h1","_tag-title":"tag-title_key","banner-desc":"","_banner-desc":"banner-desc_key","banner-image":1169,"_banner-image":"banner-image_key","banner-filter-sepia":"1","_banner-filter-sepia":"banner-filter-sepia_key","banner-image-fixed":"1","_banner-image-fixed":"banner-image-fixed_key","show-banner-logo":"0","_show-banner-logo":"banner-show-logo_key","banner-small":"1","_banner-small":"banner-small_key"},"align":"","mode":"edit"} /-->

                <!-- wp:acf/teams-block {"id":"block_6418ab0cd829d","name":"acf/teams-block","data":{"teams-title":"Trenerzy i instruktorzy:","_teams-title":"teams-title_key","teams-tag-title":"h2","_teams-tag-title":"teams-tag-title_key","teams_0_teams-name":"Dariusz Felix Dębiec","_teams_0_teams-name":"teams-name_key","teams_0_teams-position":"Trener boksu klasy I","_teams_0_teams-position":"teams-position_key","teams_0_teams-image":"","_teams_0_teams-image":"teams-image_key","teams_0_teams-description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","_teams_0_teams-description":"teams-description_key","teams_1_teams-name":"John Smith","_teams_1_teams-name":"teams-name_key","teams_1_teams-position":"Trener boksu klasy II","_teams_1_teams-position":"teams-position_key","teams_1_teams-image":"","_teams_1_teams-image":"teams-image_key","teams_1_teams-description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","_teams_1_teams-description":"teams-description_key","teams_2_teams-name":"Jan Kowalski","_teams_2_teams-name":"teams-name_key","teams_2_teams-position":"Pomocnik","_teams_2_teams-position":"teams-position_key","teams_2_teams-image":"","_teams_2_teams-image":"teams-image_key","teams_2_teams-description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.","_teams_2_teams-description":"teams-description_key","teams":3,"_teams":"teams-key"},"align":"","mode":"edit"} /-->
                
                <!-- wp:acf/banner-block {"id":"block_640c48f8bcbf3","name":"acf/banner-block","data":{"banner-title":"","_banner-title":"banner-title_key","tag-title":"h2","_tag-title":"tag-title_key","banner-desc":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","_banner-desc":"banner-desc_key","banner-image":1175,"_banner-image":"banner-image_key","banner-filter-sepia":"1","_banner-filter-sepia":"banner-filter-sepia_key","banner-image-fixed":"1","_banner-image-fixed":"banner-image-fixed_key","show-banner-logo":"0","_show-banner-logo":"banner-show-logo_key","banner-small":"0","_banner-small":"banner-small_key"},"align":"","mode":"edit"} /-->',

            ]
        );
    });
}